# -*- mode: ruby -*-
# vi: set ft=ruby :
 
Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64"
 
    config.vm.define :master do |master_config|
        master_config.vm.hostname = 'master'
        master_config.vm.network "private_network", ip: "192.168.18.10"
        master_config.vm.network "forwarded_port", guest: 8080, host: 8080
        master_config.vm.network "forwarded_port", guest: 8000, host: 8000
        master_config.vm.provision :shell, path: "master.sh"
    end
 
    
#    config.vm.define :worker do |worker_config|
#        worker_config.vm.hostname = 'worker'
#        worker_config.vm.network "private_network", ip: "192.168.18.11"
#        worker_config.vm.network "forwarded_port", guest: 8000, host: 8001
#        worker_config.vm.provision :shell, path: "worker.sh"
#    end
    
    
end
